AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DBSecretArn:
    Type: String
    Description: ARN of Secrets Manager secret for database credentials

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: nodejs20.x
    Architectures: ['arm64']
    Environment:
      Variables:
        NODE_OPTIONS: '--enable-source-maps'
    EphemeralStorage:
      Size: 512
  Api:
    OpenApiVersion: '2.0'
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"
      MaxAge: 600

Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nest-dependencies
      Description: Node modules for Nest.js application
      ContentUri: layer/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      BinaryMediaTypes:
        - 'image/*'
        - 'multipart/form-data'
      Auth:
        DefaultAuthorizer: NONE

  NestFunction:
    Type: AWS::Serverless::Function
    Metadata:
      SkipBuild: true
    Properties:
      Handler: dist/lambda.handler
      CodeUri: ./dist
      MemorySize: 3008
      Timeout: 30
      Layers:
        - !Ref NodeModulesLayer
      Policies:
        Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DBSecretArn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref Api
            Auth:
              Authorizer: NONE
      AutoPublishAlias: live
      VpcConfig:
        # 私网子网 ID（3 个，分布在不同 AZ）
        # Lambda 会在这些子网中运行
        SubnetIds:
          - subnet-0939b1a3b99d9771f
          - subnet-0f5487a66eeee1a13
          - subnet-05d7ded925a46386e
        # Lambda 安全组
        # 允许 Lambda 访问数据库（通过数据库安全组的入站规则）
        SecurityGroupIds:
          - sg-0dd2d82efc24ddd0e
      Environment:
        Variables:
          DB_SECRET_ARN: !Ref DBSecretArn
############################
# Security Group
############################
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda access to database
      VpcId: vpc-0fa0071d26df679e5
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev'
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt NestFunction.Arn
